array = [
    "Is the question asking for more details?",
    "Q. Why does DNA replicate?",
    "No",
    "Q. Can you explain me in depth?",
    "Yes",
    "Q. How does that work in more details?",
    "Yes",
    "Q. What is inside an asteroid?",
    "No",
    "Q. What is the van der waals force?",
    "No",
    "Q. Can you elaborate on that?",
    "Yes",
    "Q. What is a solar system?",
    "No",
    "Q. Can you give me more details?",
    "Yes",
    "Q. What is mars?",
    "No",
    "Q. I don't understand. Please tell me more.",
    "Yes",
    "Q. How does a computer work?",
    "No",
    "Q. What is the definition of a planet?",
    "No",
]
